# Generated by Django 4.2.14 on 2024-11-01 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrunIliskisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benzerlik_orani', models.FloatField()),
                ('kbk_urun', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='kbk_urun', to='proje.urunler')),
                ('partymarty_urun', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='partymarty_urun', to='proje.urunler')),
            ],
        ),
    ]
